name: Build, Test, and Deploy
on:
  workflow_dispatch:

jobs:
    app:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v4.2.2
          
    
          - name: Log in to GitHub Container Registry
            uses: docker/login-action@v3.0.0
            with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.GITHUB_TOKEN }}
    
          - name: Build and publish a Docker image for ${{ github.repository }}/reminderiu
            uses: macbre/push-to-ghcr@master
            with:
              dockerfile: Dockerfile
              image_name: ${{ github.repository }}/reminderiu
              github_token: ${{ secrets.GITHUB_TOKEN }}
        
    deploy:
        needs: 
        - app
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout code
            uses: actions/checkout@v4.1.1

        -   name: Copy docker-compose.yml to droplet
            uses: appleboy/scp-action@v0.1.7
            with:
                host: ${{ secrets.DROPLET_IP }}
                username: root
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                source: docker-compose.yml
                target: ./app

        -   name: Create .env file on droplet
            uses: appleboy/ssh-action@v1.1.0
            with:
                host: ${{ secrets.DROPLET_IP }}
                username: root
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                    cd ~/app
                    if [ -f .env ]; then
                        echo ".env file exists"
                    else
                        echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" > ./.env
                        echo "PREFIX=${{ secrets.PREFIX }}" >> ./.env
                        echo "GITHUB_REPOSITORY=$(echo '${{ github.repository }}' | awk '{print tolower($0)}')" >> .env
                        docker logout ghcr.io
                    fi
        

        -   name: Log in to GitHub Container Registry
            uses: docker/login-action@v3.0.0
            with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
        -   name: Deploy
            uses: appleboy/ssh-action@v1.1.0
            with:
                host: ${{ secrets.DROPLET_IP }}
                username: root
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                    cd ~/app
                    export REPO=$(echo "${{ github.repository }}" | awk '{print tolower($0)}')
                    docker compose down
                    docker pull ghcr.io/$REPO/reminderiu
                    docker compose up -d
                    docker compose logs
